### ISSUE TITLE
Ruby expressions are getting replaced with <eext>

### ISSUE THREAD

**Issue by karthikkasturi** [adamzapasnik/prettier-plugin-erb#44]
`<%= image_with_path "path" %>`

is getting replaced with 

`<eext1/> `

**Comment by molfar** [comment]
have the same issue

**Comment by adamzapasnik** [comment]
hey guys, should be fixed in a newly released v0.2.0

**Comment by karthikkasturi** [comment]
Still happening in 0.2.0

![image](https://user-images.githubusercontent.com/21277826/119475699-fd5f5b00-bd6a-11eb-8dfd-66761e1d56be.png)

![image](https://user-images.githubusercontent.com/21277826/119475725-04866900-bd6b-11eb-87b8-42320b572545.png)

**Comment by adamzapasnik** [comment]
Which prettier version are you using? 🤔 if it's 2.3 downgrade it to 2.2.x. If it's not that, then I'm gonna have a look at it tomorrow 😓

**Comment by karthikkasturi** [comment]
Downgrading to 2.2.0 helped, thanks!

**Comment by michaelzim** [comment]
Even with the latest verson I still see this happening in `<textarea>` elements.

packages:
prettier@2.2.1
@prettier/plugin-ruby@1.5.5
prettier-plugin-erb@0.3.0

input:
`<textarea><%= 123 %></textarea>`

output:
`<textarea> <eext1 /> </textarea>`

**Comment by molfar** [comment]
The same issue with newest 0.4.0. This time all <%= ... %> get replaced with <eext1 />

**Comment by abdullah-kasim** [comment]
The following `.html.erb` is an easily reproducible scenario:

```erb
<script>
  <% if CONSTANT_2 == 'asd' %>

          var a = '<%= CONSTANT_1 %>'

  <% else %>
          var a = '<%= CONSTANT_3 %>'
  <% end %>
</script>
```

On prettier 2.2.0 and 2.2.1, it produces the following:

```erb
<script>
  <% if CONSTANT_2 == 'asd' %>


            var a = '<%= CONSTANT_1 %>'


  </eext1> <eext3>
            var a = '<%= CONSTANT_3 %>'
  <% end %>
</script>
```

**Comment by mason-stewart** [comment]
This continues to be an issue in 0.4.0. Here's the dev deps from my packson.json

```json
  "devDependencies": {
    "@prettier/plugin-ruby": "^1.6.1",
    "prettier": "^2.4.0",
    "prettier-plugin-erb": "^0.4.0"
  }
```

I've confirmed that this happens in my terminal `yarn run prettier --write foo/bar.html.erb` and isn't being caused by a conflicting VS Code plugin. Thanks!

[EDIT]

For reference, per @karthikkasturi's comment above, version locking these specific versions of each dep fixes the issue:

```json
  "devDependencies": {
    "@prettier/plugin-ruby": "1.5.5",
    "prettier": "2.2.0",
    "prettier-plugin-erb": "0.2.0"
  }
```

**Comment by kvnloughead** [comment]
Same issue with the more recent versions, except is was happening with `<% %>` instead of `<%= %>`. These versions:

```json
"devDependencies": {
    "@prettier/plugin-ruby": "^3.1.2",
    "prettier": "^2.6.2",
    "prettier-plugin-erb": "^0.4.0"
  }
```

![image](https://user-images.githubusercontent.com/37159177/171526587-03a5942e-2f21-44f7-8c88-6ccdbf2c8db9.png)

Locking the versions from the post above seems to resolve _that_ issue, but created another issue, reported elsewhere, replacing `<%= foo %>` with `[object Object]` inside `<title>` . Changing to these versions seems to work

```json
{
  "devDependencies": {
    "@prettier/plugin-ruby": "1.5.5",
    "prettier": "2.2.0",
    "prettier-plugin-erb": "0.4.0"
  }
}
```

**Comment by jhandel** [comment]
I am still getting this issue even with the version locking of :

`  "devDependencies": {
    "@prettier/plugin-ruby": "1.5.5",
    "prettier": "2.2.0",
    "prettier-plugin-erb": "0.4.0"
  }`
  
  the following code turns into the following code:
  `<div
  data-controller="combobox"
  class="relative mt-1"
  data-action="click@window->combobox#windowClick"
  data-combobox-open-value="false"
  data-combobox-active-target-value="#combobox-button"
  data-combobox-active-class-value="bg-indigo-600"
  data-combobox-invisible-class-value="opacity-0 scale-95 hidden"
  data-combobox-visible-class-value="opacity-100 scale-100"
  data-combobox-entering-class-value="ease-out duration-300"
  data-combobox-enter-timeout-value="300"
  data-combobox-leaving-class-value="ease-in duration-300"
  data-combobox-leave-timeout-value="300"
  data-combobox-selected-option-class-value="combobox-selected-option"
  data-combobox-option-class-value="combobox-option"
  data-combobox-mode-value="<%= mode %>"
  data-combobox-select-fill-url-value="/locations">
  <input id="combobox" type="text" name="<%= text_field_name %>" value="<%= current_text %>" placeholder="<%= selection_place_holder %>"class=" w-full rounded-md border border-gray-300 bg-white py-2 pl-3 pr-12 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 sm:text-sm" data-action=" focus->combobox#show keydown->combobox#moveSelection input->combobox#filterList focusout->combobox#looseFocus" data-combobox-target="input" role="combobox" aria-controls="options" aria-expanded="false" >
  <input type="hidden" data-combobox-target="selection" name="<%= id_field_name %>" value="<%= current_id %>">
  <button type="button" class=" absolute inset-y-0 right-0 flex items-center rounded-r-md px-2 focus:outline-none" data-action="click->combobox#toggle" data-combobox-target="button">
    <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="currentColor" aria-hidden="true" >
      <path fill-rule="evenodd"
            d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z"
            clip-rule="evenodd"/></svg>
  </button>
  <div data-combobox-target="list" 
        class="hidden opacity-0 scale-95 absolute z-10 mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
    <ul role="listbox" >
      <% collection.each do |record| %>
        <li class="relative cursor-default select-none py-2 pl-3 pr-9"
              id="option-0"
              role="option"
              tabindex="-1"
              data-text="<%= record.send(collection_text_field_name) %>"
              data-value="<%= record.send(collection_id_field_name) %>"
              data-action="click->combobox#selected">
          <span class="block truncate "><%= record[collection_text_field_name] %></span>
          <span role="selection_flag" class="absolute inset-y-0 right-0 flex items-center pr-4">
            <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd"
                    d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                    clip-rule="evenodd"/></svg>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
</div>`

`<eext1 />
<div
  data-controller="combobox"
  class="relative mt-1"
  data-action="click@window->combobox#windowClick"
  data-combobox-open-value="false"
  data-combobox-active-target-value="#combobox-button"
  data-combobox-active-class-value="bg-indigo-600"
  data-combobox-invisible-class-value="opacity-0 scale-95 hidden"
  data-combobox-visible-class-value="opacity-100 scale-100"
  data-combobox-entering-class-value="ease-out duration-300"
  data-combobox-enter-timeout-value="300"
  data-combobox-leaving-class-value="ease-in duration-300"
  data-combobox-leave-timeout-value="300"
  data-combobox-selected-option-class-value="combobox-selected-option"
  data-combobox-option-class-value="combobox-option"
  data-combobox-mode-value="eex2eex"
  data-combobox-select-fill-url-value="/locations"
>
  <input
    id="combobox"
    type="text"
    name="eex3eex"
    value="eex4eex"
    placeholder="eex5eex"
    class=" w-full rounded-md border border-gray-300 bg-white py-2 pl-3 pr-12 shadow-sm focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 sm:text-sm"
    data-action=" focus->combobox#show keydown->combobox#moveSelection input->combobox#filterList focusout->combobox#looseFocus"
    data-combobox-target="input"
    role="combobox"
    aria-controls="options"
    aria-expanded="false"
  />
  <input
    type="hidden"
    data-combobox-target="selection"
    name="eex6eex"
    value="eex7eex"
  />
  <button
    type="button"
    class=" absolute inset-y-0 right-0 flex items-center rounded-r-md px-2 focus:outline-none"
    data-action="click->combobox#toggle"
    data-combobox-target="button"
  >
    <svg
      class="h-5 w-5 text-gray-400"
      xmlns="http://www.w3.org/2000/svg"
      fill="currentColor"
      aria-hidden="true"
    >
      <path
        fill-rule="evenodd"
        d="M10 3a1 1 0 01.707.293l3 3a1 1 0 01-1.414 1.414L10 5.414 7.707 7.707a1 1 0 01-1.414-1.414l3-3A1 1 0 0110 3zm-3.707 9.293a1 1 0 011.414 0L10 14.586l2.293-2.293a1 1 0 011.414 1.414l-3 3a1 1 0 01-1.414 0l-3-3a1 1 0 010-1.414z"
        clip-rule="evenodd"
      />
    </svg>
  </button>
  <div
    data-combobox-target="list"
    class="hidden opacity-0 scale-95 absolute z-10 mt-1 max-h-60 w-full overflow-auto rounded-md bg-white py-1 text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm"
  >
    <ul role="listbox">
      <eext8>
        <li
          class="relative cursor-default select-none py-2 pl-3 pr-9"
          id="option-0"
          role="option"
          tabindex="-1"
          data-text="eex9eex"
          data-value="eex10eex"
          data-action="click->combobox#selected"
        >
          <span class="block truncate "> <eext11 /> </span>
          <span
            role="selection_flag"
            class="absolute inset-y-0 right-0 flex items-center pr-4"
          >
            <svg
              class="h-5 w-5"
              xmlns="http://www.w3.org/2000/svg"
              viewBox="0 0 20 20"
              fill="currentColor"
              aria-hidden="true"
            >
              <path
                fill-rule="evenodd"
                d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z"
                clip-rule="evenodd"
              />
            </svg>
          </span>
        </li>
      </eext8>
    </ul>
  </div>
</div>
`

**Comment by MattBudz** [comment]
I'm seeing the same issue with:

- VSCode: 1.73.0
- Prettier: 2.7.1
- plugin-ruby: 3.2.2
- plugin-erb: 0.4.0

**Comment by drale2k** [comment]
Any solution here except downgrading way back to 2.2.0? I am having the same issue with the following versions:

```js
"@prettier/plugin-ruby": "^3.2.2",
"prettier": "^2.8.0",
"prettier-plugin-erb": "^0.4.0"
```

**Comment by ziadsawalha** [comment]
Hi @adamzapasnik - this is pretty serious issue since it can overwrite/corrupt/undo people's code. May I suggest placing a very loud warning on the readme or taking this plugin off the VS Code marketplace until it is fixed.

Especially since erb files can be treated as HTML but for the handling of these expressions, which is how I came across the plugin.

**Comment by archonic** [comment]
I version locked to the following per @mason-stewart's suggestion:
```
"devDependencies": {
  "@prettier/plugin-ruby": "1.5.5",
  "prettier": "2.2.0",
  "prettier-plugin-erb": "0.2.0"
}
```

And the following line:
```
<main role="main" class="h-full px-5 py-2 text-slate-900 dark:text-slate-50 <%= 'bg-gradient-to-tr from-slate-100 to-indigo-100 dark:from-slate-900 dark:to-indigo-900' if controller.controller_name == "static_pages" %>">
```
was changed to:
```
<main
  role="main"
  class="[object Object] h-full px-5 py-2 text-slate-900 dark:text-slate-50"
>
```

I'm not saying this to be mean, but this is a poor enough introduction to this plugin that I'm just going to abandon it.

**Comment by drewlustro** [comment]
Absolutely bizarre... my installation was working for weeks up until today. Seeing `<eext />` left and right.

My `package.json` has conservative versions pinned... not sure why this would suddenly occur.

Did something change with a VSCode update that caused everything to break?

**Comment by BaggioGiacomo** [comment]
I have the same when I've installed the `@shopify/prettier-plugin-liquid` package 👎🏻 

```json
  "@prettier/plugin-ruby": "1.6.1",
  "@shopify/prettier-plugin-liquid": "1.0.6",
  "prettier-plugin-erb": "0.4.0"
```
